### ISSUE TITLE
401: Unauthorized error

### ISSUE THREAD

**Issue by vasu-dasari** [tsloughter/kuberl#3]
Hi,

Thanks for a wonderful package kuberl. I was thinking of writing this kind of project along this lines. Maybe I can help in this project as time goes by.

For now, I am trying to execute the example code highlighted in README.md. The following might not be a bug, probably the way I am using it. 

I started minikube from my Mac OSX. And then I compiled my own app with kuberl as a dependency from a Docker container running OTP 20. And then copied the .kube from my home directory to the container's home directory, so that container can see the same kube-config.

From container I can do:

```
root@piccolo:~# kubectl get nodes
NAME       STATUS    ROLES     AGE       VERSION
minikube   Ready     <none>    46d       v1.9.0
```

I got the bearer token as follows:

`TOKEN=$(kubectl describe secret $(kubectl get secrets | grep default | cut -f1 -d ' ') | grep -E '^token' | cut -f2 -d':' | tr -d '\t')
`
Then I started my app and from Erlang shell, I set up Cfg variable and then tried to get api versions as follows:

```
(piccolo@piccolo)2> Cfg.
#{api_key_prefix => #{<<"authorization">> => <<"Bearer">>},
  auth =>
      #{'BearerToken' =>
            <<"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9"...>>},
  hackney_opts =>
      [{ssl_options,[{server_name_indication,disable}]}],
  host => "https://192.168.64.2:8443"}
(piccolo@piccolo)3> kuberl_core_api:get_api_versions(ctx:background(), #{cfg => Cfg}).
{error,#{apiVersion => <<"v1">>,code => 401,kind => <<"Status">>,
         message => <<"Unauthorized">>,metadata => #{},
         reason => <<"Unauthorized">>,status => <<"Failure">>},
       #{headers =>
             [{<<"Content-Type">>,<<"application/json">>},
              {<<"Date">>,<<"Tue, 13 Mar 2018 23:21:00 GMT">>},
              {<<"Content-Length">>,<<"129">>}],
         status => 401}}
```

May I know what is it I am doing wrong? Or do you think the way I am getting Bearer token is right?

How did you test this, like how to fetch bearer token, or test environment?

Thanks
-Vasu

**Comment by tsloughter** [comment]
I'm not sure minikube has support for bearer token authentication currently.

The easiest way is to just run `kubectl proxy` and go through that for now.

I can verify this is the issue with minikube a little later, I vaguely remember there are open issues with them and instructions on using the other methods, but when using minikube myself I simply am using the proxy with kuberl instead.

**Comment by vasu-dasari** [comment]
Thanks that works.
```
root@piccolo# kubectl proxy
Starting to serve on 127.0.0.1:8001
```
And from Erlang shell
```
(piccolo@piccolo)11> C = kuberl:cfg_with_bearer_token(kuberl:cfg_with_host("http://127.0.0.1:8001"), <<"">>).
(piccolo@piccolo)11> kuberl_core_api:get_api_versions(ctx:background(), #{cfg => C}).
{ok,#{kind => <<"APIVersions">>,
      serverAddressByClientCIDRs =>
          [#{clientCIDR => <<"0.0.0.0/0">>,
             serverAddress => <<"10.0.2.15:8443">>}],
      versions => [<<"v1">>]},
    #{headers =>
          [{<<"Content-Length">>,<<"132">>},
           {<<"Content-Type">>,<<"application/json">>},
           {<<"Date">>,<<"Wed, 14 Mar 2018 02:53:13 GMT">>}],
      status => 200}}
```
A couple of more questions:
1. Did you try by using multi-node cluster using DinD (for example using, [mirantis/kubeadm-dind-cluster](https://github.com/Mirantis/kubeadm-dind-cluster))
2. Do you expect the kuberl to be running within a Kubernetes cluster or from outside the cluster?
3. If you have tried kuberl by running from within a cluster, can you share a cheatsheet how you tried it?

**Comment by vitorenesduarte** [comment]
Hi @vasu-dasari.
[Here](https://github.com/vitorenesduarte/kuberl-example)'s a simple example with `kuberl` running within a Kubernetes cluster.

**Comment by vasu-dasari** [comment]
Thanks @vitorenesduarte. I will try this out later today.

**Comment by tsloughter** [comment]
I didn't know about `kubeadm-dind-cluster`, this definitely looks useful! I'll try it out.

kuberl is meant to be used for either, depending on the purpose of the application it is being used for.

The only use of it I know of right now is https://github.com/vitorenesduarte/tricks

I'm using it for https://github.com/spacetime-iot/vonnegut_operator but have only tested it against minikube with the proxy so far and need to push my latest code.

**Comment by vasu-dasari** [comment]
Thanks. Will close this issue for now.
